header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Canonical Ltd.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
  paths:
    - '**'
  paths-ignore:
    - '.github/**'
    - '**/*.json'
    - '**/*.md'
    - '**/*.conf'
    - '**/*.txt'
    - '**/*.sh'
    - '.jujuignore'
    - '.gitignore'
    - '.licenserc.yaml'
    - '.trivyignore'
    - '.woke.yaml'
    - '.woke.yml'
    - 'CODEOWNERS'
    - 'LICENSE'
    - 'trivy.yaml'
    - 'pyproject.toml'
    - 'zap_rules.tsv'
  comment: on-failure
