{
 "title": "Hockeypuck: Performance and Health Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mem_available_percent{juju_model='$juju_model', service=~'$application', juju_unit=~'$juju_unit'}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_used{juju_model='$juju_model', service=~'$application', juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}} - Used"
    },
    {
     "expr": "mem_free{juju_model='$juju_model', service=~'$application', juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}} - Free"
    }
   ]
  },
  { "title": "Hockeypuck metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last restart",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"} * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(hockeypuck_http_request_duration_seconds_sum{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}[5m]) / rate(hockeypuck_http_request_duration_seconds_count{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}[5m])",
     "legendFormat": "{{juju_unit}} {{method}}:{{status_code}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(hockeypuck_http_request_duration_seconds_count{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\" }[5m])) by (method, status_code)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(hockeypuck_http_request_duration_seconds_bucket{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\" }[5m])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "stat",
   "description": "Since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hockeypuck_keys_added{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "Added"
    },
    {
     "expr": "hockeypuck_keys_updated{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "Updated"
    },
    {
     "expr": "hockeypuck_keys_ignored{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "Ignored"
    }
   ]
  },
  {
   "title": "Keys overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "hockeypuck_keys_added{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "Added"
    },
    {
     "expr": "hockeypuck_keys_updated{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "Updated"
    },
    {
     "expr": "hockeypuck_keys_ignored{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "Ignored"
    }
   ]
  },
  { "title": "Go metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'} - go_memstats_other_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "bytes of memory are used for other runtime allocations {instance={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}} - heap allocation"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}} - heap idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}} -heap inuse"
    },
    {
     "expr": "go_memstats_heap_released_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}} - heap released"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"} - go_memstats_frees_total{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}[5m])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total: counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}[5m])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}[5m])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Hockeypuck Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit', instance=~\".*:9626\"}",
     "legendFormat": "{{juju_unit}} - quantile:{{quantile}}"
    }
   ]
  },
  { "title": "$application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 }, "repeat": "application" },
  {
   "title": "go routines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(increase(hockeypuck_http_request_duration_seconds_bucket{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}} - quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum(increase(conflux_reconciliation_duration_seconds_bucket{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "go memstat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}[2m])",
     "legendFormat": "{{juju_unit}} - rate(total) 30s"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}} - stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}} - heap_inuse_bytes"
    }
   ]
  },
  {
   "title": "Number of \"dirmngr\" processes",
   "type": "timeseries",
   "description": "cRT#124887 cRT#127175",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "procstat_lookup_pid_count{exe=\"dirmngr\", juju_model='$juju_model', service=~'$application',  juju_unit=~'$juju_unit'}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  }
 ]
}