#!/bin/bash

# Delete keys from the Hockeypuck postgres database by fingerprint

set -euo pipefail

if [[ -z "${APP_DELETE_FINGERPRINTS}" || -z "${TICKET_ID}" ]]; then
    cat <<EOF
Usage: APP_DELETE_FINGERPRINTS="FP1,FP2,FP3" TICKET_ID="TICKET123" $0

APP_DELETE_FINGERPRINTS should be a comma-separated string of fingerprints to be deleted.
TICKET_ID should be the corresponding GDPR ticket ID.
EOF
    exit 1
fi

SQLCMD="PGPASSWORD=${POSTGRESQL_DB_PASSWORD} psql ${POSTGRESQL_DB_NAME} -h ${POSTGRESQL_DB_HOSTNAME} -U ${POSTGRESQL_DB_USERNAME}"

echo "Deleting fingerprints: $APP_DELETE_FINGERPRINTS for ticket: $TICKET_ID"

$SQLCMD -c 'create table if not exists deleted_keys (fingerprint text primary key not null, comment text not null);'

IFS=',' read -ra fp_array <<< "$APP_DELETE_FINGERPRINTS"
for fp in "${fp_array[@]}"; do
  $SQLCMD -c "insert into deleted_keys (fingerprint, comment) values ('$fp', '$TICKET_ID') on conflict do nothing;"
done

$SQLCMD -c '
  delete from subkeys k using deleted_keys b where k.rfingerprint = lower(reverse(b.fingerprint));
  alter table subkeys drop constraint subkeys_rfingerprint_fkey;
  delete from keys k using deleted_keys b where k.rfingerprint = lower(reverse(b.fingerprint));
  alter table subkeys add foreign key (rfingerprint) references keys(rfingerprint);
' 