name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
      pre-run-script: |
        -c "sudo apt update && sudo apt install psycopg2-binary"
